name: Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          make test
